# Taken from https://github.com/hashbang/shell-server/blob/797cec330b69fcc022581593aba42c0cd4641133/ansible/tasks/profile/main.yml#L97
- name: Remove default /etc/skel directory
  block:
    - name: Create /etc/skel/.profile
      ansible.builtin.file:
        path: /etc/skel/.profile
        state: absent

    - name: Create /etc/skel/.bash_logout
      ansible.builtin.file:
        path: /etc/skel/.bash_logout
        state: absent

    - name: Create /etc/skel/.bashrc
      ansible.builtin.file:
        path: /etc/skel/.bashrc
        state: absent

    - name: Create /etc/skel/.kshrc
      ansible.builtin.file:
        path: /etc/skel/.kshrc
        state: absent

    - name: Create /etc/skel/.mkshrc
      ansible.builtin.file:
        path: /etc/skel/.mkshrc
        state: absent

- name: Override the useradd command configuration
  ansible.builtin.replace:
    path: /etc/default/useradd
    regexp: "# SKEL"
    replace: "SKEL"

- name: Create the config directory if not exists
  ansible.builtin.file:
    path: /etc/skel/.config
    state: directory
    mode: "0755"
    recurse: true

- name: Copy the fish configuration directory
  ansible.builtin.copy:
    src: ../../common/files/fish
    dest: /etc/skel/.config
    mode: "0755"
    force: true

- name: Copy the tmux configuration file
  ansible.builtin.copy:
    src: ../../common/files/.tmux.conf
    dest: /etc/skel/
    mode: "0644"
    force: true
