- name: Create external Docker networks
  community.docker.docker_network:
    name: "{{ item }}"
    state: present
    driver: bridge
  loop:
    - homelab
    - ldap
    - monitoring

- name: Create the external Docker volumes
  ansible.builtin.file:
    path: "{{ docker_dir }}/media"
    state: directory
    mode: "0755"
