- name: Create the LibreSpeed application directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/librespeed/data/config"
    state: directory
    mode: "0755"

- name: Create LibreSpeed container managed by Docker
  community.docker.docker_container:
    name: librespeed
    image: lscr.io/linuxserver/librespeed:latest
    state: started
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
      PASSWORD: "{{ librespeed_password }}"
    volumes:
      - "{{ docker_dir }}/librespeed/data/config:/config"
    restart_policy: unless-stopped
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.librespeed-secure.middlewares: "authentik@file"
      traefik.http.routers.librespeed-secure.entrypoints: "https"
      traefik.http.routers.librespeed-secure.rule: "Host(`speed.{{ domain }}`)"
      traefik.http.routers.librespeed-secure.tls: "true"
      traefik.http.routers.librespeed-secure.service: "librespeed-svc"
      traefik.http.services.librespeed-svc.loadBalancer.server.port: "80"
      traefik.http.routers.librespeed-secure.tls.certresolver: letsencrypt
      traefik.http.routers.librespeed-secure.tls.domains[0].main: "{{ domain }}"
      traefik.http.routers.librespeed-secure.tls.domains[0].sans: "*.{{ domain }}"
      traefik.docker.network: homelab
