- name: Include services task files
  ansible.builtin.include_tasks: "{{ task_name }}.yml"
  loop:
    - docker
    - traefik
    - authentik
    - portainer
    - uptime_kuma
    - dashy
    - jellyfin
    - duplicati
    - prometheus
    - grafana
  loop_control:
    loop_var: task_name
