- name: Include services task files
  ansible.builtin.include_tasks: "{{ task_name }}.yml"
  loop:
    - docker
    - traefik
    - authentik
    - portainer
    - dashy
    - jellyfin
    - duplicati
    - prometheus
    - grafana
    - nextcloud
    # - owncloud
    - uptime_kuma
    - wireguard
    - librespeed
    - vaultwarden
    - prowlarr
    - radarr
    - sonarr
    - jellyseerr
    - qbittorrent
  loop_control:
    loop_var: task_name
