- name: Create the Prowlarr directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/prowlarr/data/config"
    state: directory
    mode: "0755"
    owner: 1000
    group: 1000

- name: Create Prowlarr container managed by Docker
  community.docker.docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
    volumes:
      - "{{ docker_dir }}/prowlarr/data/config:/config"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.prowlarr-secure.middlewares: "authentik@file"
      traefik.http.routers.prowlarr-secure.entrypoints: "https"
      traefik.http.routers.prowlarr-secure.rule: "Host(`prowlarr.{{ domain }}`)"
      traefik.http.routers.prowlarr-secure.tls: "true"
      traefik.http.routers.prowlarr-secure.service: "prowlarr-svc"
      traefik.http.services.prowlarr-svc.loadBalancer.server.port: "9696"
      traefik.http.routers.prowlarr-secure.tls.certresolver: letsencrypt
      traefik.http.routers.prowlarr-secure.tls.domains[0].main: "{{ domain }}"
      traefik.http.routers.prowlarr-secure.tls.domains[0].sans: "*.{{ domain }}"
      traefik.docker.network: homelab
