- name: Create the qBittorrent directories
  ansible.builtin.file:
    path: "{{ docker_dir }}/qbittorrent/data/config"
    state: directory
    mode: "0755"

- name: Create the qBittorrent media subdirectories
  ansible.builtin.file:
    path: "{{ media_dir }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: 1000
    group: 1000
  loop:
    - torrents
    - movies
    - tv

- name: Create qBittorrent container managed by Docker
  community.docker.docker_container:
    name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
      WEBUI_PORT: "8080"
      TORRENTING_PORT: "6881"
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "{{ docker_dir }}/qbittorrent/data/config:/config"
      - "{{ media_dir }}/torrents:/torrents"
      - "{{ media_dir }}/movies:/movies"
      - "{{ media_dir }}/tv:/tv"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.qbittorrent-secure.middlewares: "authentik@file"
      traefik.http.routers.qbittorrent-secure.entrypoints: "https"
      traefik.http.routers.qbittorrent-secure.rule: "Host(`qbittorrent.{{ domain }}`)"
      traefik.http.routers.qbittorrent-secure.tls: "true"
      traefik.http.routers.qbittorrent-secure.service: "qbittorrent-svc"
      traefik.http.services.qbittorrent-svc.loadBalancer.server.port: "8080"
      traefik.http.routers.qbittorrent-secure.tls.certresolver: letsencrypt
      traefik.http.routers.qbittorrent-secure.tls.domains[0].main: "{{ domain }}"
      traefik.http.routers.qbittorrent-secure.tls.domains[0].sans: "*.{{ domain }}"
      traefik.docker.network: homelab
