- name: Create the Vaultwarden application directories
  ansible.builtin.file:
    path: "{{ docker_dir }}/vaultwarden/data/data"
    state: directory
    mode: "0755"

- name: Create Vaultwarden container managed by Docker
  community.docker.docker_container:
    name: vaultwarden
    image: vaultwarden/server
    state: started
    env:
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
      SMTP_HOST: "{{ mailer_smtp_host }}"
      SMTP_FROM: "{{ mailer_smtp_from }}"
      SMTP_PORT: "{{ mailer_smtp_port }}"
      SMTP_SECURITY: "{{ mailer_smtp_security }}"
      SMTP_USERNAME: "{{ mailer_smtp_username }}"
      SMTP_PASSWORD: "{{ mailer_smtp_password }}"
      DOMAIN: "https://vaultwarden.{{ domain }}"
    volumes:
      - "{{ docker_dir }}/vaultwarden/data/data:/data:rw"
    restart_policy: unless-stopped
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.vaultwarden-secure.middlewares: "authentik@file"
      traefik.http.routers.vaultwarden-secure.entrypoints: "https"
      traefik.http.routers.vaultwarden-secure.rule: "Host(`vaultwarden.{{ domain }}`)"
      traefik.http.routers.vaultwarden-secure.tls: "true"
      traefik.http.routers.vaultwarden-secure.service: "vaultwarden-svc"
      traefik.http.services.vaultwarden-svc.loadBalancer.server.port: "80"
      traefik.http.routers.vaultwarden-secure.tls.certresolver: letsencrypt
      traefik.http.routers.vaultwarden-secure.tls.domains[0].main: "{{ domain }}"
      traefik.http.routers.vaultwarden-secure.tls.domains[0].sans: "*.{{ domain }}"
      traefik.docker.network: homelab
